version: '3'

services:
  # Database
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
  # WordPress
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
  # Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
     - "1080:80"
     - "10443:443"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
     - php
    networks:
     - wpsite
  # PHP-FPM   
  php:
    image: php:7-fpm-alpine
    container_name: php-fpm
    volumes:
    ./work_dir:/work_dir
    ports:
     - "9000:9000"       
    networks:
     - wpsite


networks:
  wpsite:
volumes:
  db_data:
