version: '4'
services:
  php-fpm:
    image: php-fpm:latest
    container_name: php-fpm
    ports:
    - 9000:9000
    networks:
      - lemp_net

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:8080
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wp_example_db
    volumes:
      - wordpress:/var/www/html
    networks:
      - lemp_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - lemp_net

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp_example_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - lemp_net

networks:
  lemp_net:
    driver: bridge

volumes:
  wordpress :
  mysql-data:
    driver: local
