version: '4'
services:
  php-fpm:
    image: php-fpm:latest
    container_name: php-fpm
    ports:
    - 9000:9000
    networks:
      - lemp_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - lemp_net

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lemp_compose_test_db
      MYSQL_ROOT_PASSWORD: password123
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
      - lemp_net

networks:
  lemp_net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
